(setq load-path (cons "~/.emacs.d/" load-path))
(load "paths")
(load "requires")
(load "hooks")
(load "fonts")
(load "vars")
(load "keys")
(load "pastie")
(load "gitsum")
(load "color-theme")
(load "color-theme-autoloads")
(load "color-theme-library")
(load "inf-ruby")
(load "rubydb3x")

(require 'vc-git)
 (when (featurep 'vc-git) (add-to-list 'vc-handled-backends 'git))
 (require 'git)

(load-library "xscheme")

(load "misc")