(setq load-path (cons "~/.emacs.d/" load-path))
(load "paths")
(load "requires")
(load "hooks")
(load "fonts")
(load "vars")
(load "keys")
(load "gitsum")
(load "color-theme")
(load "color-theme-autoloads")
(load "color-theme-library")
(load "inf-ruby")
(load "rubydb3x")
(load "rspec")
(load "abbrev")
(load "temp_files")
(load "nxml")
(load "shells")
(load "quack")
(load "gist")
(load "haskell-site-file")
(load "textmate")
(textmate-mode)
(require 'quack)
(require 'vc-git)
 (when (featurep 'vc-git) (add-to-list 'vc-handled-backends 'git))
(require 'git)
(require 'rinari)


(load-library "xscheme")
(load "misc")