(server-start)
(display-time)
(line-number-mode 1)
(column-number-mode 1)
(color-theme-andreas)
(menu-bar-mode)
(tool-bar-mode nil)
(scroll-bar-mode)
(global-font-lock-mode t)
(show-paren-mode 1)
(visit-tags-table "~/programacion/rbx/TAGS")
