(server-start)
(display-time)
(line-number-mode 1)
(column-number-mode 1)
(color-theme-zenburn)
(menu-bar-mode)
(tool-bar-mode nil)
(scroll-bar-mode)
(global-font-lock-mode t)
(show-paren-mode 1)
(set-frame-height (selected-frame) 37)
(set-frame-width (selected-frame) 120)
(set-frame-position (selected-frame) 50 40)
(prefer-coding-system 'utf-8)

