(setq load-path (cons "~/.emacs.d/vendor"  load-path))
(setq load-path (cons "~/.emacs.d/vendor/themes" load-path))
(setq load-path (cons "~/.emacs.d/vendor/themes" load-path))
(setq load-path (cons "~/.emacs.d/vendor/themes" load-path))
(setq load-path (cons "~/.emacs.d/vendor/ruby" load-path))
(setq load-path (cons "~/.emacs.d/vendor/haskell" load-path))
(setq load-path (cons "~/.emacs.d/vendor/git" load-path))
(setq load-path (cons "~/.emacs.d/vendor/rinari" load-path))
(setq load-path (cons "~/.emacs.d/vendor/nxml" load-path))
(setq load-path (cons "~/.emacs.d/vendor/textmate.el" load-path))

