(setq scroll-bar-mode nil)
(setq mac-command-modifier 'meta) 
(setq inhibit-startup-message t)	
(setq make-backup-files nil) 
(setq user-mail-address "federico.builes@gmail.com")
(setq user-full-name "Federico Builes")
(setq search-highlight t)
(setq query-replace-highlight t)
(setq default-fill-column 77)
(setq c-tab-always-indent "other") 
(setq rinari-tags-file-name "TAGS")
(setq ispell-dictionary "spanish")

