(cond ((string= system-type "gnu/linux")
       (set-face-attribute 'default nil :height 185)
       (global-set-key [(control -)] 'font-smaller)
       (global-set-key [(control \+)] 'font-larger)
       (global-disable-mouse-mode))
      ((string= system-type "darwin")
       (set-default-font "-unknown-Inconsolata-normal-normal-normal-*-*-*-*-*-m-0-iso10646-1")
       (set-face-attribute 'default nil :height 260)
       (global-set-key [(meta -)] 'font-smaller)
       (global-set-key [(meta \+)] 'font-larger)))
